<?xml version='1.0'?>
<robot name="fyp_robot" xmlns:xacro="http://ros.org/wiki/xacro">
<!-- ixx ixy ixz
     ixy iyy iyz
     ixz iyz izz -->

  <xacro:property name="base_xy" value="0.5" />
  <xacro:property name="b_base_z" value="0.3" />
  <xacro:property name="t_base_z" value="0.5" />
  <xacro:property name="wheeldiam" value="0.2" />
  <xacro:property name="casterradi" value="0.06" />
  <xacro:property name="wheellength" value="0.05" />
  <xacro:property name="pi" value="3.1415" />
  <xacro:property name="caster_mass" value="1" />
  <xacro:property name="wheel_mass" value="5" />
  <xacro:property name="base_mass" value="10" />

  <xacro:property name="base_xy2" value="${base_xy*base_xy}" />

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>
  <xacro:macro name="cuboid_inertial" params="mass height"> <!--solid cuboid macro-->
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="${(1/12)*mass*(height*height+base_xy2)}" ixy="0.0" ixz="0.0" iyy="${(1/12)*mass*(base_xy2*2)}" iyz="0.0" izz="${(1/12)*mass*(base_xy2+height*height)}" />
    </inertial>
  </xacro:macro>
  <xacro:macro name="sphere_inertial" params="mass height radius"> <!--solid sphere macro-->
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="${(2/5)*mass*radius*radius}" ixy="0.0" ixz="0.0" iyy="${(2/5)*mass*radius*radius}}" iyz="0.0" izz="${(2/5)*mass*radius*radius}" />
    </inertial>
  </xacro:macro>

<!-- Add the rectangular base -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_xy} ${base_xy} ${b_base_z}"/> <!-- 0.5 x 0.5 x 1.0 -->
      </geometry> 
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_xy} ${base_xy} ${b_base_z}"/> <!-- 0.5 x 0.5 x 1.0 -->
      </geometry>
    </collision>
    <xacro:cuboid_inertial mass="${base_mass}" height="${b_base_z}"/>
  </link>

<!-- add caster to each corner of the robot using a macro-->
  <xacro:macro name="caster" params="prefix1 prefix2 reflect1 reflect2">
    <link name="caster_${prefix1}_${prefix2}">
      <visual>
        <geometry>
          <sphere radius="${casterradi}"/>
        </geometry>
        <material name="white"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
       <geometry>
          <sphere radius="${casterradi}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </collision>
      <xacro:default_inertial mass="${caster_mass}"/>
    </link>
    <joint name="caster_${prefix1}_${prefix2}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="caster_${prefix1}_${prefix2}"/>
      <origin xyz="${0.19*reflect2} ${-0.19*reflect1} -0.15" rpy="0 0 0"/>
    </joint>
  </xacro:macro> 
<!-- end of creating caster macro-->
  <xacro:caster prefix1="front" prefix2="left" reflect1="1" reflect2="1" />
  <xacro:caster prefix1="front" prefix2="right" reflect1="1" reflect2="-1" />
  <xacro:caster prefix1="back" prefix2="left" reflect1="-1" reflect2="1" />
  <xacro:caster prefix1="back" prefix2="right" reflect1="-1" reflect2="-1" />
<!-- add left & right wheels to the robot -->
  <xacro:macro name="wheels" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder length="${wheellength}" radius="${wheeldiam/2}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      </visual>
      <collision>
       <geometry>
          <cylinder length="${wheellength}" radius="${wheeldiam/2}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      </collision>
      <xacro:default_inertial mass="${wheel_mass}"/>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
        <origin xyz="${0.225*reflect} 0 -0.115" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  <xacro:wheels prefix="left" reflect="1" />
  <xacro:wheels prefix="right" reflect="-1" />

<!-- add the top part to the robot -->
  <link name="base_back">
    <visual>
      <geometry>
        <box size="0.3 0.01 0.2"/>
      </geometry>
      <origin xyz="0 0.245 0.25" rpy="0 0 0"/>
    </visual>
    <collision>
     <geometry>
        <box size="0.3 0.01 0.2"/>
      </geometry>
      <origin xyz="0 0.245 0.25" rpy="0 0 0"/>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>
  <joint name="base_back_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_back"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_top">
    <visual>
      <geometry>
        <box size="${base_xy} ${base_xy} ${t_base_z}"/>
      </geometry>
      <origin xyz="0 0 0.6" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_xy} ${base_xy} ${t_base_z}"/>
      </geometry>
      <origin xyz="0 0 0.6" rpy="0 0 0"/>
    </collision>
    <xacro:cuboid_inertial mass="${base_mass}" height="${t_base_z}"/>
  </link>
  <joint name="base_top_joint" type="fixed">
    <parent link="base_back"/>
    <child link="base_top"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

</robot>
